export {default as Navbar} from './Navbar/Navbar';
export {default as InfoSection} from './InfoSection/InfoSection';
export {default as Footer} from './Footer/Footer';
export {default as Services} from './Services/Services';
export {default as TypesServices} from './TypesServices/TypesServices';
export {default as CaseStudy} from './CaseStudy/CaseStudy';
export {default as CapBanner} from './CapBanner/CapBanner';
export {default as AboutWeb} from './AboutWeb/AboutWeb';
export {default as AboutChoose} from './AboutChoose/AboutChoose';
export {default as AboutText} from './AboutText/AboutText';
export {default as ServiceBanner} from './ServicesBanner/ServiceBanner';
export {default as ServiceType} from './ServiceType/ServiceType';
export {default as ServiceText} from './ServiceText/ServiceText';
export {default as ContactBanner} from './ContactBanner/ContactBanner'
export {default as ContactInfo} from './ContactInfo/ContactInfo'
export {default as SuccessText} from './SuccessText/SuccessText'
export {default as Testimonial} from './Testimonial/Testimonail'
export {default as SeoContent} from './SeoContent/SeoContent'
export{default as SeoContentBanner} from './SeoContentBanner/SeoContentBanner'
export {default as SeoContentOne} from './SeoContentOne/SeoContentOne'
export {default as SeoContentProcess} from './SeoContentProcess/SeoContentProcess'
export {default as SeoContentLast} from './SeoContentLast/SeoContentLast'